### ISSUE TITLE
Question on Autofocus

### ISSUE THREAD

**Issue by jameszah** [0015/ESP32-OV5640-AF#1]
I haven't tried this yet - but it looks excellent!

https://github.com/0015/ESP32-OV5640-AF/blob/e3c18173181c8cca4de39ef967f88ca43757d519/src/ESP32_OV5640_cfg.h#L34

Do you know what this microcode actually does?  Is there source code that could be modified?  Or an 5640 microcode programming manual?
  
Is it your understanding that the esp32-camera driver does not have that auto-focus microcode?  
I thought it did, but as I look at it right now, it is not there, so the standard esp32 drivers must leave it in infinity focus mode.

I've seen a few similar things like this, but never put the time to understand it.

https://www.its304.com/article/hwytree/118992955
https://gitlab.com/k2wl/g2_kernel/-/blob/4472ce5be96571f65dcfad53a6aa32c58d5553bd/drivers/media/video/msm/ov5640.h#L1046

**Comment by 0015** [comment]
@jameszah It's not about esp32-camera but OV5640 module. It can be used if the camera module has an auto-focusing function. The microcode is for OV5640 firmware settings.
