### ISSUE TITLE
Use OV5640 with ESP-WROVER-KIT?

### ISSUE THREAD

**Issue by freeride01** [0015/ESP32-OV5640-AF#10]
Hi,
I want to use ESP-WROVER-KIT with the Waveshare OV5640 board. I installed the ESP32-OV5640-AF library, but:
1. The CameraWebServer example does not support OV5640
2. The OV5640_Console_Test is for ESP32 AI-THINKER Board only, it seems.

How can I use ESP-WROVER-KIT with the Waveshare OV5640 cam board?

Thanks.

**Comment by 0015** [comment]
@freeride01 The CameraWebServer example supports OV5640. After checking the PID to automatically display the expanded menu. For this, your board and OV5640 must be properly connected. How about checking the pin out of the ESP-WROVER-KIT again? https://docs.espressif.com/projects/esp-idf/en/latest/esp32/hw-reference/esp32/get-started-wrover-kit.html

**Comment by freeride01** [comment]
Hi @0015,
it doesn't seem like pin connections are the problem.
This is the pinout of the camera connector on the ESP-WROVER-KIT:

![kitPinout](https://github.com/0015/ESP32-OV5640-AF/assets/69974416/1a83e91d-b36f-47d3-b9bc-a8eb3cc7865e),

this is the pinout of the OV5640 board:

![boardPinout](https://github.com/0015/ESP32-OV5640-AF/assets/69974416/2f94e4af-eaee-4de9-b033-61b4e4397885), 

and here is the code that maps them to each other:

CameraWebServer.ino:

 `config.pin_d0 = Y2_GPIO_NUM;`
 `config.pin_d1 = Y3_GPIO_NUM;`
 `config.pin_d2 = Y4_GPIO_NUM;`
 `config.pin_d3 = Y5_GPIO_NUM;`
 `config.pin_d4 = Y6_GPIO_NUM;`
 `config.pin_d5 = Y7_GPIO_NUM;`
 `config.pin_d6 = Y8_GPIO_NUM;`
 `config.pin_d7 = Y9_GPIO_NUM;`

camera_pins.h:

`#if defined(CAMERA_MODEL_WROVER_KIT)`
`.........`
`#define Y9_GPIO_NUM      35`
`#define Y8_GPIO_NUM      34`
`#define Y7_GPIO_NUM      39`
`#define Y6_GPIO_NUM      36`
`#define Y5_GPIO_NUM      19`
`#define Y4_GPIO_NUM      18`
`#define Y3_GPIO_NUM       5`
`#define Y2_GPIO_NUM       4`

So everything seems fine.

However, I noticed in the code there are no references to OV5640, like in CameraWebServer.ino the only PID mentioned is OV3660_PID, and in camera_index.h there are only index files for OV2640 and OV3660.

`index_ov2640.html.gz, Size: 4316`
`index_ov3660.html.gz, Size: 4408`

Maybe there is another version of the example with support for OV5640?

**Comment by 0015** [comment]
@freeride01 Please check the official ESP32-camera GitHub page. https://github.com/espressif/esp32-camera
As you can see here, it supports OV5640 officially. 

![image](https://github.com/0015/ESP32-OV5640-AF/assets/9106382/c89997ab-5156-4533-b362-9b693ba2700f)
in the CameraWebServer Example, open the file, app_httpd.cpp
Depending on the PID value, it loads each HTML file.

**Comment by freeride01** [comment]
Yes, the problem was I was using an old version of the arduino-esp32 BSP.
After I updated it, the project now includes support for OV5640.
Thank you!
