### ISSUE TITLE
Use in conjuction with Espressif esp32-camera esp_camera_init?

### ISSUE THREAD

**Issue by jasaw** [0015/ESP32-OV5640-AF#11]
Fantastic work on getting autofocus to work on the ESP32 !

I'm using the Espressif esp32-camera `esp_camera_init` function to initialize my camera. Question is when do I call your `ov5640.focusInit()` function? I see that your `focusInit()` resets the camera and loads the autofocus firmware to the camera and this is going to cause havoc if `focusInit()` is called after `esp_camera_init` ?

My camera init code looks something like this:
```
  esp_err_t err = esp_camera_init(&config);
  if (err != ESP_OK) {
    return;
  }
```

**Comment by 0015** [comment]
@jasaw To set this autofocus register, you first need esp_camera_sensor_get. Also, if I'm correct, to get esp_camera_sensor_get, esp_camera_init() needs to be done first. Therefore, the steps below were necessary.
esp_camera_init function() -> ov5640.start(esp_camera_sensor_get()) -> ov5640.focusInit()
Also, ov5640.focusInit() does not initialize the camera but only changes the sensor register. Why do you think there is an issue with this?

**Comment by jasaw** [comment]
Thank you for your prompt response. Now that you have clarified it and I have taken another close look at your `OV5640_Console_Test.ino` example code, it is clear to me how your autofocus code is meant to be used with the Espressif SDK.
Thank you again for this much needed functionality.
