### ISSUE TITLE
Board modification seems to be wrong; AF-VCC is pin 4 of camera connector

### ISSUE THREAD

**Issue by SchneHa** [0015/ESP32-OV5640-AF#2]
I tried with ESP32-CAM board but something seems to be wrong. I connected 3V3 to pin 24 of camera connector but produced a shortcut. I looked at pin 24 and found out it's connected to GND. Datasheet of OV5640 says that AF-VCC is pin 4 and not 24 and pin 4 has 3V3. What is going wrong?

**Comment by 0015** [comment]
@SchneHa That's weird. In the datasheet I have, pin 24 is AF-VCC. Check this out. https://www.waveshare.com/w/upload/c/c4/OV5640-C.pdf

**Comment by SchneHa** [comment]
@0015  Ah, I see. I found another pinout in this datasheet: https://arducam.com/downloads/modules/OV5640/OV5640_Software_app_note_parallel.pdf
and it works on my ESP32-CAM board without any modification.

**Comment by SchneHa** [comment]
@0015 You should update the section Hardware Modification of your readme. There seems to exist 2 different kinds of OV5640 cameras.

**Comment by 0015** [comment]
@SchneHa You're right. I updated the readme page. Thanks.
