### ISSUE TITLE
Auto focus doesnt work 

### ISSUE THREAD

**Issue by jasonhongpro** [0015/ESP32-OV5640-AF#4]
Hello, 

I tried replicating the result on my esp32 cam, but the auto focus function doesn't work. I bought a slightly different version of the ov5640 model, which has Auto-VDD at pin #23 instead of #24, and I did connect that pin to the 3V power pin from the board accordingly. I ran the unmodified example code you provided, and the monitor console did indeed show the camera was focusing and focused. However, I didn't hear any sounds from the motor while the camera was focusing, nor did I get a clear picture when I took a shot with it. Any thoughts on what could cause it? I tried it on several camera modules from different vendors, same result. 

This is the one I bought.

<img width="568" alt="Screenshot 2022-07-29 144105" src="https://user-images.githubusercontent.com/7472262/181702983-db4367fc-3fe7-430c-a89a-9dd6882440de.png">

**Comment by 0015** [comment]
@jasonhongpro It looks different from what I have. Unfortunately, I didn't have an OV5640 from another manufacturer, so I couldn't test it. Would you like to see this?
![Screen Shot 2022-08-01 at 12 55 05 PM](https://user-images.githubusercontent.com/9106382/182234180-97d49987-24d6-4426-995f-c309d83e5305.png)

**Comment by ankurphutela** [comment]
@jasonhongpro did you find any solution? I am also using same camera module.
