### ISSUE TITLE
AF-VCC powering

### ISSUE THREAD

**Issue by Kabron287** [0015/ESP32-OV5640-AF#7]
It is more correct to connect the autofocus module power to 2.8V. 
There is an appropriate regulator on the ESP32CAM board.

**Comment by 0015** [comment]
@Kabron287 I see but there is no pinout for 2.8v even if it has an appropriate regulator. How did you handle it?

**Comment by Kabron287** [comment]
Seek and ye shall find
![2 8V](https://github.com/0015/ESP32-OV5640-AF/assets/2493191/5b60ac04-6c31-496d-aeed-9bbabe007689)
![Cam](https://github.com/0015/ESP32-OV5640-AF/assets/2493191/f4e38903-ff5a-4db6-a109-dce50f48d4ed)
