### ISSUE TITLE
Autofocus not working with Arducam OV5640D

### ISSUE THREAD

**Issue by amisbs** [0015/ESP32-OV5640-AF#8]
I am using the [Arducam module](https://www.arducam.com/product/5-mp-ov5640d-cmos-af-camera-module-1-4-inch-module/), which appears to be very similar to the [one from Waveshare](https://www.waveshare.com/wiki/OV5640_Camera_Board_(C)), however the camera is not focusing.

I have tried implementing the basic example.

I can confirm the camera emits a click when it is connected to a power supply, which seems to confirm that the autofocus coil is actually connected.

**Comment by 0015** [comment]
@amisbs It looks similar, but I can't check the command for auto-focusing because there is no data sheet.
